<?php

namespace App\Workflows;

use App\Repositories\BaseRepository;
use App\Services\MailService;
use App\Core\Database;
use Exception;
use PDO;

class TaskManager
{
    private BaseRepository $tareaRepository;

    public function __construct(BaseRepository $tareaRepository)
    {
        $this->tareaRepository = $tareaRepository;
    }

    /**
     * Completes an existing task and triggers the creation of the next one(s).
     */
    public function completeTask(int $taskId, int $userId, array $workflowContext = []): bool
    {
        $tarea = $this->tareaRepository->findById($taskId);
        
        if (!$tarea) {
            throw new Exception("La tarea no existe");
        }

        if ($tarea['estado'] === 'COMPLETADA') {
            throw new Exception("La tarea ya fue completada");
        }

        // Check assigned user
        if ($tarea['assigned_to'] !== null && $tarea['assigned_to'] != $userId) {
            throw new Exception("No tienes permiso para completar esta tarea");
        }

        // Marcar tarea como completada
        $updatedData = [
            'estado' => 'COMPLETADA',
            'completed_at' => date('Y-m-d H:i:s')
        ];

        return $this->tareaRepository->update($taskId, $updatedData);
    }

    /**
     * Creates a new pending user task generated by the ProcessEngine
     */
    public function createNextTask(int $procesoId, int $expedienteId, string $titulo, ?string $descripcion, ?int $assignedToAreaId = null, ?int $assignedToUserId = null, string $prioridad = 'NORMAL'): int
    {
        $data = [
            'proceso_id' => $procesoId,
            'expediente_id' => $expedienteId,
            'titulo' => $titulo,
            'descripcion' => $descripcion,
            'estado' => 'PENDIENTE',
            'prioridad' => $prioridad,
            // si se asigna a área, el controlador se encargará de buscar un usuario, o task lists grupales
            'assigned_to' => $assignedToUserId
        ];

        $taskId = $this->tareaRepository->create($data);

        // Disparar Notificación de Correo Institucional
        if ($assignedToUserId) {
            try {
                $db = Database::getInstance();
                $stmt = $db->prepare('SELECT email FROM users WHERE id = :id');
                $stmt->execute([':id' => $assignedToUserId]);
                $user = $stmt->fetch();
                
                if ($user && !empty($user['email'])) {
                    $mailService = new MailService();
                    // Simular codigo de expediente ya que solo tenemos el ID aquí
                    $expCode = "EXP-".date('Y')."-".str_pad($expedienteId, 4, "0", STR_PAD_LEFT);
                    $mailService->sendTaskNotification($user['email'], $titulo, $expCode);
                }
            } catch (Exception $e) {
                // Falla silenciosa para no interrumpir el workflow si el correo falla
                error_log("Fallo al enviar notificación de tarea: " . $e->getMessage());
            }
        }

        return $taskId;
    }
}
